//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Servicio_General.WS_Servicio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_ServicioSoap", Namespace="Sistemas Integral")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta))]
    public partial class WS_Servicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Procesar_ServicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Obtener_Servicio_ConstanteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Servicio() {
            this.Url = global::Servicio_General.Properties.Settings.Default.Servicio_General_WS_Servicio_WS_Servicio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Procesar_ServicioCompletedEventHandler Procesar_ServicioCompleted;
        
        /// <remarks/>
        public event Obtener_Servicio_ConstanteCompletedEventHandler Obtener_Servicio_ConstanteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Sistemas Integral/Procesar_Servicio", RequestNamespace="Sistemas Integral", ResponseNamespace="Sistemas Integral", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RS_Servicio Procesar_Servicio(int pId_Servicio, short pCantidad_Errores_Continuos, string pUltimo_Error) {
            object[] results = this.Invoke("Procesar_Servicio", new object[] {
                        pId_Servicio,
                        pCantidad_Errores_Continuos,
                        pUltimo_Error});
            return ((RS_Servicio)(results[0]));
        }
        
        /// <remarks/>
        public void Procesar_ServicioAsync(int pId_Servicio, short pCantidad_Errores_Continuos, string pUltimo_Error) {
            this.Procesar_ServicioAsync(pId_Servicio, pCantidad_Errores_Continuos, pUltimo_Error, null);
        }
        
        /// <remarks/>
        public void Procesar_ServicioAsync(int pId_Servicio, short pCantidad_Errores_Continuos, string pUltimo_Error, object userState) {
            if ((this.Procesar_ServicioOperationCompleted == null)) {
                this.Procesar_ServicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesar_ServicioOperationCompleted);
            }
            this.InvokeAsync("Procesar_Servicio", new object[] {
                        pId_Servicio,
                        pCantidad_Errores_Continuos,
                        pUltimo_Error}, this.Procesar_ServicioOperationCompleted, userState);
        }
        
        private void OnProcesar_ServicioOperationCompleted(object arg) {
            if ((this.Procesar_ServicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Procesar_ServicioCompleted(this, new Procesar_ServicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Sistemas Integral/Obtener_Servicio_Constante", RequestNamespace="Sistemas Integral", ResponseNamespace="Sistemas Integral", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RS_Servicio_Constante Obtener_Servicio_Constante(int pId_Servicio) {
            object[] results = this.Invoke("Obtener_Servicio_Constante", new object[] {
                        pId_Servicio});
            return ((RS_Servicio_Constante)(results[0]));
        }
        
        /// <remarks/>
        public void Obtener_Servicio_ConstanteAsync(int pId_Servicio) {
            this.Obtener_Servicio_ConstanteAsync(pId_Servicio, null);
        }
        
        /// <remarks/>
        public void Obtener_Servicio_ConstanteAsync(int pId_Servicio, object userState) {
            if ((this.Obtener_Servicio_ConstanteOperationCompleted == null)) {
                this.Obtener_Servicio_ConstanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtener_Servicio_ConstanteOperationCompleted);
            }
            this.InvokeAsync("Obtener_Servicio_Constante", new object[] {
                        pId_Servicio}, this.Obtener_Servicio_ConstanteOperationCompleted, userState);
        }
        
        private void OnObtener_Servicio_ConstanteOperationCompleted(object arg) {
            if ((this.Obtener_Servicio_ConstanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Obtener_Servicio_ConstanteCompleted(this, new Obtener_Servicio_ConstanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Sistemas Integral")]
    public partial class RS_Servicio : Respuesta {
        
        private OServicio servicioField;
        
        /// <remarks/>
        public OServicio Servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Sistemas Integral")]
    public partial class OServicio {
        
        private int id_ServicioField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private System.Nullable<System.DateTime> fecha_Hora_Ultimo_ControlField;
        
        private string observaciones_Ultimo_ControlField;
        
        private System.Nullable<int> id_NotificacionField;
        
        private string nombre_NotificacionField;
        
        private int id_Notificacion_ErrorField;
        
        private bool aplica_LunesField;
        
        private bool aplica_MartesField;
        
        private bool aplica_MiercolesField;
        
        private bool aplica_JuevesField;
        
        private bool aplica_ViernesField;
        
        private bool aplica_SabadoField;
        
        private bool aplica_DomingoField;
        
        private bool aplica_FeriadosField;
        
        private bool aplica_Periodo_VacacionalField;
        
        private short id_Servicio_TipoField;
        
        private string nombre_Servicio_TipoField;
        
        private short id_Servicio_EstadoField;
        
        private string nombre_Servicio_EstadoField;
        
        private bool registra_ProcesamientoField;
        
        /// <remarks/>
        public int Id_Servicio {
            get {
                return this.id_ServicioField;
            }
            set {
                this.id_ServicioField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fecha_Hora_Ultimo_Control {
            get {
                return this.fecha_Hora_Ultimo_ControlField;
            }
            set {
                this.fecha_Hora_Ultimo_ControlField = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones_Ultimo_Control {
            get {
                return this.observaciones_Ultimo_ControlField;
            }
            set {
                this.observaciones_Ultimo_ControlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Id_Notificacion {
            get {
                return this.id_NotificacionField;
            }
            set {
                this.id_NotificacionField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre_Notificacion {
            get {
                return this.nombre_NotificacionField;
            }
            set {
                this.nombre_NotificacionField = value;
            }
        }
        
        /// <remarks/>
        public int Id_Notificacion_Error {
            get {
                return this.id_Notificacion_ErrorField;
            }
            set {
                this.id_Notificacion_ErrorField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Lunes {
            get {
                return this.aplica_LunesField;
            }
            set {
                this.aplica_LunesField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Martes {
            get {
                return this.aplica_MartesField;
            }
            set {
                this.aplica_MartesField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Miercoles {
            get {
                return this.aplica_MiercolesField;
            }
            set {
                this.aplica_MiercolesField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Jueves {
            get {
                return this.aplica_JuevesField;
            }
            set {
                this.aplica_JuevesField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Viernes {
            get {
                return this.aplica_ViernesField;
            }
            set {
                this.aplica_ViernesField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Sabado {
            get {
                return this.aplica_SabadoField;
            }
            set {
                this.aplica_SabadoField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Domingo {
            get {
                return this.aplica_DomingoField;
            }
            set {
                this.aplica_DomingoField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Feriados {
            get {
                return this.aplica_FeriadosField;
            }
            set {
                this.aplica_FeriadosField = value;
            }
        }
        
        /// <remarks/>
        public bool Aplica_Periodo_Vacacional {
            get {
                return this.aplica_Periodo_VacacionalField;
            }
            set {
                this.aplica_Periodo_VacacionalField = value;
            }
        }
        
        /// <remarks/>
        public short Id_Servicio_Tipo {
            get {
                return this.id_Servicio_TipoField;
            }
            set {
                this.id_Servicio_TipoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre_Servicio_Tipo {
            get {
                return this.nombre_Servicio_TipoField;
            }
            set {
                this.nombre_Servicio_TipoField = value;
            }
        }
        
        /// <remarks/>
        public short Id_Servicio_Estado {
            get {
                return this.id_Servicio_EstadoField;
            }
            set {
                this.id_Servicio_EstadoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre_Servicio_Estado {
            get {
                return this.nombre_Servicio_EstadoField;
            }
            set {
                this.nombre_Servicio_EstadoField = value;
            }
        }
        
        /// <remarks/>
        public bool Registra_Procesamiento {
            get {
                return this.registra_ProcesamientoField;
            }
            set {
                this.registra_ProcesamientoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Sistemas Integral")]
    public partial class OServicio_Constante {
        
        private int control_Cada_X_SegundosField;
        
        private string hora_InicioField;
        
        private string hora_FinField;
        
        /// <remarks/>
        public int Control_Cada_X_Segundos {
            get {
                return this.control_Cada_X_SegundosField;
            }
            set {
                this.control_Cada_X_SegundosField = value;
            }
        }
        
        /// <remarks/>
        public string Hora_Inicio {
            get {
                return this.hora_InicioField;
            }
            set {
                this.hora_InicioField = value;
            }
        }
        
        /// <remarks/>
        public string Hora_Fin {
            get {
                return this.hora_FinField;
            }
            set {
                this.hora_FinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RS_Servicio_Constante))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RS_Servicio))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Sistemas Integral")]
    public partial class Respuesta {
        
        private Resultado resultadoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public Resultado Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Sistemas Integral")]
    public enum Resultado {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Ok,
        
        /// <remarks/>
        Advertencia,
        
        /// <remarks/>
        Confirmacion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Sistemas Integral")]
    public partial class RS_Servicio_Constante : Respuesta {
        
        private OServicio_Constante servicioField;
        
        /// <remarks/>
        public OServicio_Constante Servicio {
            get {
                return this.servicioField;
            }
            set {
                this.servicioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Procesar_ServicioCompletedEventHandler(object sender, Procesar_ServicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Procesar_ServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Procesar_ServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RS_Servicio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RS_Servicio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Obtener_Servicio_ConstanteCompletedEventHandler(object sender, Obtener_Servicio_ConstanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Obtener_Servicio_ConstanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Obtener_Servicio_ConstanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RS_Servicio_Constante Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RS_Servicio_Constante)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591